[package]
name = "acars_router"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
log = "0.4.17"
env_logger = "0.9.0"
chrono = "0.4.0"
tokio = { version = "1.18.2", features = ["full", "tracing"] }
tokio-util = { version = "0.7.3", features = ["full"] }
tokio-stream = "0.1.9"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
derive-getters = "0.2.0"
queue = "0.3.0"
