---
name: Deploy

on:
  workflow_dispatch:
    inputs:
      reason:
        required: true
        description: "Reason for running this workflow"
  push:
    branches:
      - main

    # Don't trigger if it's just a documentation update
    paths-ignore:
      - "**.md"
      - "**.MD"
      - "**.yml"
      - "LICENSE"
      - ".gitattributes"
      - ".gitignore"
      - ".dockerignore"

jobs:
  workflow-dispatch:
    name: Workflow Dispatch
    # only run this step if workflow dispatch triggered
    # log the reason the workflow dispatch was triggered
    if: |
      github.event_name == 'workflow_dispatch' &&
      github.event.inputs.reason != ''
    runs-on: ubuntu-latest
    steps:
      - name: Log dispatch reason
        env:
          INPUTS_REASON: ${{ github.event.inputs.reason }}
        run: |
          echo "Workflow dispatch reason: $INPUTS_REASON"
          echo "::notice title=${{ github.job }}: Workflow Dispatch Reason::${INPUTS_REASON}"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    secrets:
      ghcr_token: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # https://github.com/marketplace/actions/docker-on-tmpfs
      # https://github.com/rust-lang/cargo/issues/8719
      # https://github.com/rust-lang/cargo/issues/9545

      - name: Run Docker on tmpfs
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        uses: JonasAlfredsson/docker-on-tmpfs@v1
        with:
          tmpfs_size: 5
          swap_size: 4
          swap_location: "/mnt/swapfile"

      - name: Build
        uses: sdr-enthusiasts/common-github-workflows/.github/workflows/build_and_push_image.yml@main
        with:
          push_enabled: true
          push_destinations: ghcr.io
          ghcr_repo_owner: ${{ github.repository_owner }}
          ghcr_repo: ${{ github.repository }}
